force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventAttendance__c/EventAttendance__c.object-meta.xml
<CustomObject>
    <label>Event Attendance</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EventAttendance__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Event Attendances</relationshipLabel>
    <relationshipName>Event_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EventAttendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Attendances</relationshipLabel>
    <relationshipName>Event_Attendances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/controllers/EventAttendanceFormController.cls
public with sharing class EventAttendanceFormController {
    @AuraEnabled
    public static Id save(Event__c event, List<Attendee__c> attendees) {
        Savepoint savepoint = Database.setSavepoint();

        try {
            Security.stripInaccessible(AccessType.CREATABLE, new List<Event__c>{ event });

            insert event;

            Security.stripInaccessible(AccessType.CREATABLE, attendees);

            upsert attendees Email__c;

            List<EventAttendance__c> eventAttendances = new List<EventAttendance__c>();
            for (Attendee__c attendee : attendees) {
                eventAttendances.add(new EventAttendance__c(Event__c = event.Id, Attendee__c = attendee.Id));
            }

            Security.stripInaccessible(AccessType.UPSERTABLE, eventAttendances);

            insert eventAttendances;

            return event.Id;
        } catch (Exception ex) {
            Database.rollback(savepoint);
            AuraHandledException auraException = new AuraHandledException(ex.getMessage());
            auraException.setMessage(ex.getMessage());
            throw auraException;
        }
    }
}