force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirth__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <label>Event Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <inlineHelpText
    >URL or web address of the website, platform or application that will be used to host the event. Examples include Zoom, Google Meet, Skype, Microsoft Teams, etc.</inlineHelpText>
    <label>Place</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Event Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/EventAttendance__c/EventAttendance__c.object-meta.xml
<CustomObject>
    <label>Event Attendance</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EventAttendance__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Event Attendances</relationshipLabel>
    <relationshipName>Event_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EventAttendance__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Attendances</relationshipLabel>
    <relationshipName>Event_Attendances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/tests/EventAttendanceFormControllerTest.cls
@IsTest
private class EventAttendanceFormControllerTest {
    @IsTest
    private static void shouldSaveSucessfully() {
        Id adminProfileId = [SELECT Id, Name FROM Profile WHERE name = 'System Administrator' LIMIT 1].Id;
        User user = TestUtils.createTestUser(adminProfileId, 'Test', 'User');
        insert user;

        Event__c expectedEvent = TestUtils.createTestEvent('Special heyCloud event');
        Attendee__c expectedAttendee = TestUtils.createTestAttendee(
            'john.doe@heycloud.com',
            Date.today().addYears(-18)
        );

        Test.startTest();
        System.runAs(user) {
            EventAttendanceFormController.save(expectedEvent, new List<Attendee__c>{ expectedAttendee });
        }
        Test.stopTest();

        List<Event__c> actualEvents = [SELECT Id, EventName__c, StartDate__c, Place__c, Description__c FROM Event__c];
        List<Attendee__c> actualAttendees = [
            SELECT Id, FirstName__c, LastName__c, DateOfBirth__c, Email__c
            FROM Attendee__c
        ];
        List<EventAttendance__c> actualEventAttendances = [SELECT Id, Event__c, Attendee__c FROM EventAttendance__c];

        System.assertEquals(false, actualEvents.isEmpty(), 'Evenets should not be empty');
        System.assertEquals(
            expectedEvent.EventName__c,
            actualEvents.get(0).EventName__c,
            'Event name should be equal to expected value'
        );
        System.assertEquals(
            expectedEvent.StartDate__c,
            actualEvents.get(0).StartDate__c,
            'Event date should be equal to expected value'
        );
        System.assertEquals(
            expectedEvent.Place__c,
            actualEvents.get(0).Place__c,
            'Event place should be equal to expected value'
        );
        System.assertEquals(
            expectedEvent.Description__c,
            actualEvents.get(0).Description__c,
            'Event description should be equal to expected value'
        );

        System.assertEquals(false, actualAttendees.isEmpty(), 'Attendees should not be empty');
        System.assertEquals(
            expectedAttendee.FirstName__c,
            actualAttendees.get(0).FirstName__c,
            'Attendee first name should be equal to expected value'
        );
        System.assertEquals(
            expectedAttendee.LastName__c,
            actualAttendees.get(0).LastName__c,
            'Attendee last name should be equal to expected value'
        );
        System.assertEquals(
            expectedAttendee.DateOfBirth__c,
            actualAttendees.get(0).DateOfBirth__c,
            'Attendee date of birth should be equal to expected value'
        );
        System.assertEquals(
            expectedAttendee.Email__c,
            actualAttendees.get(0).Email__c,
            'Attendee date of birth should be equal to expected value'
        );

        System.assertEquals(false, actualEventAttendances.isEmpty(), 'Event Attendances should not be empty');
        System.assertEquals(
            actualEvents.get(0).Id,
            actualEventAttendances.get(0).Event__c,
            'Event Id should be equal to expected value'
        );
        System.assertEquals(
            actualAttendees.get(0).Id,
            actualEventAttendances.get(0).Attendee__c,
            'Attendee Id should be equal to expected value'
        );
    }

    @IsTest
    private static void shoudThrowValiation() {
        Id adminProfileId = [SELECT Id, Name FROM Profile WHERE name = 'System Administrator' LIMIT 1].Id;
        User user = TestUtils.createTestUser(adminProfileId, 'Test', 'User');
        insert user;

        Event__c expectedEvent = TestUtils.createTestEvent('Special heyCloud event');
        Attendee__c expectedAttendee = TestUtils.createTestAttendee('john.doe@heycloud.com', Date.today());

        Exception actualException;

        Test.startTest();
        System.runAs(user) {
            try {
                EventAttendanceFormController.save(expectedEvent, new List<Attendee__c>{ expectedAttendee });
            } catch (AuraHandledException ex) {
                actualException = ex;
            }
        }
        Test.stopTest();

        List<Event__c> actualEvents = [SELECT Id, Name, StartDate__c, Place__c, Description__c FROM Event__c];

        System.assertEquals(true, actualEvents.isEmpty(), 'Evenets should be empty');
        System.assert(
            actualException.getMessage().contains('Attendee cannot be under 18 years old'),
            'Exception message should contains expected value'
        );
    }

    @IsTest
    private static void shoudThrowAccess() {
        Id readOnlyProfileId = [SELECT Id, Name FROM Profile WHERE name = 'Read Only' LIMIT 1].Id;
        User user = TestUtils.createTestUser(readOnlyProfileId, 'Test', 'User');
        insert user;

        Event__c expectedEvent = TestUtils.createTestEvent('Special heyCloud event');
        Attendee__c expectedAttendee = TestUtils.createTestAttendee(
            'john.doe@heycloud.com',
            Date.today().addYears(-18)
        );

        Exception actualException;

        Test.startTest();
        System.runAs(user) {
            try {
                EventAttendanceFormController.save(expectedEvent, new List<Attendee__c>{ expectedAttendee });
            } catch (AuraHandledException ex) {
                actualException = ex;
            }
        }
        Test.stopTest();

        System.assert(
            actualException.getMessage().contains('No access to entity'),
            'Exception message should contains expected value'
        );
    }
}